const configs: { [key: string]: string[] } = {
	topType: ["LongHairStraight", "LongHairStraight2", "LongHairStraightStrand"],
	accessoriesType: ["Prescription01", "Prescription02"],
	hatColor: [
		"Black",
		"Blue01",
		"Blue02",
		"Blue03",
		"Gray01",
		"Gray02",
		"Heather",
		"PastelBlue",
		"PastelGreen",
		"PastelOrange",
		"PastelRed",
		"PastelYellow",
		"Pink",
		"Red",
		"White",
	],
	hairColor: [
		"Auburn",
		"Black",
		"Blonde",
		"BlondeGolden",
		"Brown",
		"BrownDark",
		"PastelPink",
		"Platinum",
		"Red",
		"SilverGray",
	],
	clotheType: [
		"BlazerShirt",
		"BlazerSweater",
		"CollarSweater",
		"GraphicShirt",
		"Hoodie",
		"Overall",
		"ShirtCrewNeck",
		"ShirtScoopNeck",
		"ShirtVNeck",
	],
	clotheColor: [
		"Black",
		"Blue01",
		"Blue02",
		"Blue03",
		"Gray01",
		"Gray02",
		"Heather",
		"PastelBlue",
		"PastelGreen",
		"PastelOrange",
		"PastelRed",
		"PastelYellow",
		"Pink",
		"Red",
		"White",
	],
	graphicType: [
		"Bat",
		"Cumbia",
		"Deer",
		"Diamond",
		"Hola",
		"Pizza",
		"Resist",
		"Selena",
		"Bear",
		"SkullOutline",
		"Skull",
	],
	eyeType: ["Squint", "Wink", "WinkWacky"],
	eyebrowType: [
		"Angry",
		"AngryNatural",
		"Default",
		"DefaultNatural",
		"FlatNatural",
		"RaisedExcited",
		"RaisedExcitedNatural",
		"SadConcerned",
		"SadConcernedNatural",
		"UnibrowNatural",
		"UpDown",
		"UpDownNatural",
	],
	mouthType: [
		"Concerned",
		"Default",
		"Disbelief",
		"Eating",
		"Grimace",
		"Sad",
		"ScreamOpen",
		"Serious",
		"Smile",
		"Tongue",
		"Twinkle",
		"Vomit",
	],
	skinColor: ["Yellow", "Pale", "Light"],
};

const configKeys = Object.keys(configs);

export function generateRandomAvatarOptions() {
	const options: { [key: string]: string } = {};
	const keys = [...configKeys];
	keys.forEach((key) => {
		const configArray = configs[key];
		options[key] = configArray[Math.floor(Math.random() * configArray.length)];
	});

	return options;
}
